[2024-08-29T02:55:00.033+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-29T02:55:00.065+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: country_data_pipeline.transform_data manual__2024-08-29T02:49:39.659985+00:00 [queued]>
[2024-08-29T02:55:00.090+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: country_data_pipeline.transform_data manual__2024-08-29T02:49:39.659985+00:00 [queued]>
[2024-08-29T02:55:00.091+0000] {taskinstance.py:2856} INFO - Starting attempt 2 of 2
[2024-08-29T02:55:00.136+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): transform_data> on 2024-08-29 02:49:39.659985+00:00
[2024-08-29T02:55:00.142+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=503) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-29T02:55:00.142+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'country_data_pipeline', 'transform_data', 'manual__2024-08-29T02:49:39.659985+00:00', '--job-id', '171', '--raw', '--subdir', 'DAGS_FOLDER/welcome_dags.py', '--cfg-path', '/tmp/tmp_4sl8uer']
[2024-08-29T02:55:00.144+0000] {standard_task_runner.py:72} INFO - Started process 512 to run task
[2024-08-29T02:55:00.144+0000] {standard_task_runner.py:105} INFO - Job 171: Subtask transform_data
[2024-08-29T02:55:00.225+0000] {task_command.py:467} INFO - Running <TaskInstance: country_data_pipeline.transform_data manual__2024-08-29T02:49:39.659985+00:00 [running]> on host c63ae693b587
[2024-08-29T02:55:00.364+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='country_data_pipeline' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-29T02:49:39.659985+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-29T02:49:39.659985+00:00'
[2024-08-29T02:55:00.367+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-29T02:55:00.466+0000] {logging_mixin.py:190} INFO - Cảnh báo: Cột 'translations' không tồn tại. Bỏ qua xử lý translations.
[2024-08-29T02:55:00.508+0000] {logging_mixin.py:190} INFO - Chuyển đổi dữ liệu hoàn tất.
[2024-08-29T02:55:00.510+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-08-29T02:55:00.529+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-29T02:55:00.530+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=country_data_pipeline, task_id=transform_data, run_id=manual__2024-08-29T02:49:39.659985+00:00, execution_date=20240829T024939, start_date=20240829T025500, end_date=20240829T025500
[2024-08-29T02:55:00.602+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-29T02:55:00.649+0000] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-29T02:55:00.663+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
